-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2018-10-09 21:31:49 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE agendamento CASCADE CONSTRAINTS;

DROP TABLE agendamento_servico CASCADE CONSTRAINTS;

DROP TABLE catalogo CASCADE CONSTRAINTS;

DROP TABLE cliente CASCADE CONSTRAINTS;

DROP TABLE endereco CASCADE CONSTRAINTS;

DROP TABLE profissional CASCADE CONSTRAINTS;

DROP TABLE servico CASCADE CONSTRAINTS;

CREATE TABLE agendamento (
    cod_agd    NUMBER(5) NOT NULL,
    data_agd   VARCHAR2(14) NOT NULL,
    hora_agd   VARCHAR2(14) NOT NULL,
    cod_cli    NUMBER(5) NOT NULL,
    cod_prof   NUMBER(5) NOT NULL,
    obs        VARCHAR2(200),
    cod_end    NUMBER(5)
);

COMMENT ON COLUMN agendamento.cod_agd IS
    'Código de referencia ao agendamento';

COMMENT ON COLUMN agendamento.data_agd IS
    'Data de quando o serviço será executado';

COMMENT ON COLUMN agendamento.hora_agd IS
    'Horário pelo qual o serviço será executado';

COMMENT ON COLUMN agendamento.cod_cli IS
    'Código de referencia para o cliente';

COMMENT ON COLUMN agendamento.cod_prof IS
    'Código de referencia do profissional';

COMMENT ON COLUMN agendamento.obs IS
    'Observações referentes ao serviço a ser executado';

COMMENT ON COLUMN agendamento.cod_end IS
    'Código de referencia ao endereço';

ALTER TABLE agendamento ADD CONSTRAINT agendamento_pk PRIMARY KEY ( cod_agd,
                                                                    cod_cli );

CREATE TABLE agendamento_servico (
    cod_srv   NUMBER(5) NOT NULL,
    cod_cat   NUMBER(5) NOT NULL,
    cod_agd   NUMBER(5) NOT NULL,
    cod_cli   NUMBER(5) NOT NULL
);

COMMENT ON COLUMN agendamento_servico.cod_srv IS
    'Código do serviço';

COMMENT ON COLUMN agendamento_servico.cod_cat IS
    'Código da categoria';

COMMENT ON COLUMN agendamento_servico.cod_agd IS
    'Código de agendamento';

COMMENT ON COLUMN agendamento_servico.cod_cli IS
    'Código do cliente';

ALTER TABLE agendamento_servico
    ADD CONSTRAINT agendamento_servico_pk PRIMARY KEY ( cod_srv,
                                                        cod_cat,
                                                        cod_agd,
                                                        cod_cli );

CREATE TABLE catalogo (
    cod_cat    NUMBER(5) NOT NULL,
    desc_cat   VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN catalogo.cod_cat IS
    'Código de referencia usado para o catalogo de serviços do profissional';

COMMENT ON COLUMN catalogo.desc_cat IS
    'Descrição da categoria de serviços';

ALTER TABLE catalogo ADD CONSTRAINT catalogo_pk PRIMARY KEY ( cod_cat );

CREATE TABLE cliente (
    cod_cli          NUMBER(5) NOT NULL,
    nome_cli         VARCHAR2(30) NOT NULL,
    tel_cli          VARCHAR2(16) NOT NULL,
    email_cli        VARCHAR2(50) NOT NULL,
    social_url_cli   VARCHAR2(80)
);

COMMENT ON COLUMN cliente.cod_cli IS
    'Código que referencia o cliente';

COMMENT ON COLUMN cliente.nome_cli IS
    'Nome do cliente';

COMMENT ON COLUMN cliente.tel_cli IS
    'Telefone de contato do cliente';

COMMENT ON COLUMN cliente.email_cli IS
    'E-mail de contato para cadastro';

COMMENT ON COLUMN cliente.social_url_cli IS
    'Campo para usuário de rede social do cliente';

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( cod_cli );

CREATE TABLE endereco (
    cod_end      NUMBER(5) NOT NULL,
    logradouro   VARCHAR2(80) NOT NULL,
    cidade       VARCHAR2(50) NOT NULL,
    cep          VARCHAR2(9) NOT NULL,
    estado       VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN endereco.cod_end IS
    'Código de referencia ao endereço';

COMMENT ON COLUMN endereco.logradouro IS
    'Nome da rua, avenida onde se situa';

COMMENT ON COLUMN endereco.cidade IS
    'Nome da cidade ';

COMMENT ON COLUMN endereco.cep IS
    'O CEP relacionado a residencia';

COMMENT ON COLUMN endereco.estado IS
    'Estado onde se reside';

ALTER TABLE endereco ADD CONSTRAINT endereco_pk PRIMARY KEY ( cod_end );

CREATE TABLE profissional (
    cod_prof            NUMBER(5) NOT NULL,
    nome_prof           VARCHAR2(30) NOT NULL,
    tel_prof            VARCHAR2(16) NOT NULL,
    reg_prof            VARCHAR2(30) NOT NULL,
    social_url_1_prof   VARCHAR2(80),
    social_url_2_prof   VARCHAR2(80)
);

COMMENT ON COLUMN profissional.cod_prof IS
    'Código de referencia a um profissional';

COMMENT ON COLUMN profissional.nome_prof IS
    'Nome do profissional';

COMMENT ON COLUMN profissional.tel_prof IS
    'Telefone de contato do profissional';

COMMENT ON COLUMN profissional.reg_prof IS
    'Código de registro do profissional';

COMMENT ON COLUMN profissional.social_url_1_prof IS
    'Rede social do profissional';

COMMENT ON COLUMN profissional.social_url_2_prof IS
    'Rede social do profissional';

ALTER TABLE profissional ADD CONSTRAINT profissional_pk PRIMARY KEY ( cod_prof );

CREATE TABLE servico (
    cod_srv     NUMBER(5) NOT NULL,
    qnt_srv     NUMBER(2) NOT NULL,
    valor_srv   NUMBER(6,2) NOT NULL,
    desc_srv    VARCHAR2(100) NOT NULL,
    cod_cat     NUMBER(5) NOT NULL
);

COMMENT ON COLUMN servico.cod_srv IS
    'Código de serviço';

COMMENT ON COLUMN servico.qnt_srv IS
    'Código de serviço';

COMMENT ON COLUMN servico.valor_srv IS
    'Valor do serviço';

COMMENT ON COLUMN servico.desc_srv IS
    'Descrição do serviço';

COMMENT ON COLUMN servico.cod_cat IS
    'Código de referencia a categoria';

ALTER TABLE servico ADD CONSTRAINT servico_pk PRIMARY KEY ( cod_srv,
                                                            cod_cat );

ALTER TABLE agendamento
    ADD CONSTRAINT agendamento_cliente_fk FOREIGN KEY ( cod_cli )
        REFERENCES cliente ( cod_cli );

ALTER TABLE agendamento
    ADD CONSTRAINT agendamento_endereco_fk FOREIGN KEY ( cod_end )
        REFERENCES endereco ( cod_end );

ALTER TABLE agendamento
    ADD CONSTRAINT agendamento_profissional_fk FOREIGN KEY ( cod_prof )
        REFERENCES profissional ( cod_prof );

ALTER TABLE agendamento_servico
    ADD CONSTRAINT agendamento_servico_agd_fk FOREIGN KEY ( cod_agd,
                                                            cod_cli )
        REFERENCES agendamento ( cod_agd,
                                 cod_cli );

ALTER TABLE agendamento_servico
    ADD CONSTRAINT agendamento_servico_servico_fk FOREIGN KEY ( cod_srv,
                                                                cod_cat )
        REFERENCES servico ( cod_srv,
                             cod_cat );

ALTER TABLE servico
    ADD CONSTRAINT servico_catalogo_fk FOREIGN KEY ( cod_cat )
        REFERENCES catalogo ( cod_cat );

        
-- Sequencias
        
drop sequence RM79935.SEQ_AGENDAMENTO_SERVICO;
drop sequence RM79935.SEQ_AGENDAMENTO;
drop sequence RM79935.SEQ_SERVICO;
drop sequence RM79935.SEQ_PROFISSIONAL;
drop sequence RM79935.SEQ_CLIENTE;
drop sequence RM79935.SEQ_ENDERECO;
drop sequence RM79935.SEQ_CATALOGO;

CREATE SEQUENCE  "RM79935"."SEQ_AGENDAMENTO_SERVICO"  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1;      
  
CREATE SEQUENCE  "RM79935"."SEQ_AGENDAMENTO"  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1;

CREATE SEQUENCE  "RM79935"."SEQ_SERVICO"  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1;
         
CREATE SEQUENCE  "RM79935"."SEQ_PROFISSIONAL"  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1;

CREATE SEQUENCE  "RM79935"."SEQ_CLIENTE"  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1;
 
CREATE SEQUENCE  "RM79935"."SEQ_ENDERECO"  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1;

CREATE SEQUENCE  "RM79935"."SEQ_CATALOGO"  
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1;